language: android
dist: trusty
jdk: oraclejdk8
env:
  global:
    - ANDROID_ABI=armeabi-v7a
  matrix:
    - ANDROID_TARGET=android-17
    - ANDROID_TARGET=android-27
android:
  components:
    # The BuildTools used by us
    - build-tools-28.0.3

    # The SDK we build against
    - ${ANDROID_TARGET}

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew lint
  - ./gradlew test

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches
    - $HOME/.android/build-cache
