#!/bin/sh

URL="https://m.facebook.com/language.php"

(
    echo -e "<!-- \n" \
            "!!! AUTOMATICALLY GENERATED - DO NOT CHANGE !!!\n" \
            "\n" \
            "Generated by scripts/fb-languages.sh on $(date -Is)\n" \
            "\n" \
            "//-->"
    echo "<languages>"
    curl -H "accept-language:en-US,en" ${URL} \
        | xmllint --html --xpath "//*[@id='root']/*//table/tr/td[last()]/*/a" - \
        | xmllint --html --xmlout - \
        | xmlstarlet sel -t -m "//*/a" -v "." -o "|" -v "@href" -n \
        | sort - \
        | sed -e "s#\(.*\)|/a/language.php?l=\([a-zA-Z_]*\).*#<language code=\"\2\" name=\"\1\"/>#g"
    echo "</languages>"
) | XMLLINT_INDENT="    " xmllint --format --xmlout - \
  | recode html

